name: Euro2016Flags
favicon: null
layout_spectrum: 0.5000298130325973
typography_spectrum: 0.5425502986181527
title: Euro 2016 Flags and Bunting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.160879050148651
  lightness: 0.6969116644468158
  saturation: 0.14069281332194805
  rhythmicContrast: 0.7609496358782053
purpose: []
