name: Euro2016Flags
favicon: null
layout_spectrum: 0.5000298130325973
typography_spectrum: 0.5425502986181527
title: Euro 2016 Flags and Bunting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e11d21'
    - '#000000'
    - '#fdd116'
    - '#029f50'
  brandStrength: 1
  lightness: 1
  saturation: 0.14069281332194805
  rhythmicContrast: 1
purpose: []
